
happy = input("Are you happy? ")

def stupid_function():
    print("I AM STUPID")

if happy == "YES":
    penup()
    left(90)
    backward(100)
    right(90)
    color("yellow")
    pendown()
    begin_fill()
    circle(100)
    end_fill()
    penup()
    left(90)
    color("black")
    forward(155)
    left(90)
    backward(40)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    penup()
    forward(80)
    pendown()
    begin_fill()
    circle(10)
    end_fill()
    penup()
    left(90)
    forward(100)
    pendown()
    pensize(5)
    circle(40, 180)
    stupid_function()